apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: hello-world-api
      custom:
        buildCommand: ./build.sh
        dependencies:
          paths:
            - src/**/*
            - pom.xml
            - Dockerfile
#  tagPolicy:
#    sha256: {}
deploy:
  kubectl:
    manifests:
      - k8s-*.yaml
#portForward:
#  - resourceType: service
#    resourceName: hello-world-api
#    port: 8080
#    localPort: 8080
#profiles:
#  - name: dev
#    build:
#      local:
#        push: false
#    deploy:
#      kubectl: {}
#    dev:
#      auto: true